---
title: "Part 3: Regression Models - Model 7"
author: "David Spellman"
date: "12/9/2021"
output: html_document
---

## Load packages
```{r, load_tidyverse}
library(tidyverse)
library(caret)
```

## Read data

The code chunk below reads in the final project data.  

```{r, read_final_data}
df <- readr::read_csv("cs_1675_fall2021_finalproject.csv", col_names = TRUE)
```

The `readr::read_csv()` function displays the data types and column names associated with the data. However, a glimpse is shown below that reveals the number of rows and also shows some of the representative values for the columns.  

```{r, show_data_glimpse}
dft <- df %>% mutate(output=boot::logit(output))

bfm_df <- dft
bf_df <- bfm_df %>% select(-m)

efm_df <- dft %>% mutate(x5 = 1.0 - (x1+x2+x3+x4), w=x2/(x3+x4), z=(x1+x2)/(x4+x5), t=v1*v2)
ef_df <- efm_df %>% select(-m)

ef_df %>% glimpse()
```

###7. Neural network

```{r}
set.seed(2021)
my_ctrl <- trainControl(method = "repeatedcv", number = 10, repeats = 5)
my_metric <- "RMSE"

nnet_1 <- train(output ~ .,
                data = ef_df,
                method = "nnet",
                metric = my_metric,
                preProcess = c("center", "scale"),
                trControl = my_ctrl,
                trace = FALSE,
                linout = TRUE)

#nnet_1 %>% coefplot::coefplot() + theme_bw() + theme(legend.position='none')
```


```{r}
nnet_1 %>% readr::write_rds("part_3_model_7.rds")
```

```{r}
re_load_lm_7 <- readr::read_rds("part_3_model_7.rds")
re_load_lm_7 %>% summary()
```



  

