---
title: "Final Project for 1675"
subtitle: "Part IIA: Linear Models: mod8"
author: "David Spellman"
date: "12/5/2021"
output: html_document
---

## Loading packages

```{r, load_tidyverse}
library(tidyverse)
library(tidymodels)
library(mltools)
library(caret)
```

## Reading in data

```{r, read_final_data}
df <- readr::read_csv("cs_1675_fall2021_finalproject.csv", col_names = TRUE)
```

```{r, build_data_frames}
dft <- df %>% mutate(logit_response = boot::logit (output)) %>% select (-output)
bfm_df <- dft
bf_df <- dft %>% select (-m)
efm_df <- dft %>% mutate (x5=(1-x1+x2+x3+x4), t=v1+v2, w=(x2/(x3+x4)), z=(x1+x2)/(x4+x5))
efm_df %>% glimpse()
ef_df <- efm_df %>% tibble::as_tibble () %>% select (-m)
```

### First try out some non-bayesian linear models. 

```{r, training_specs}
my_ctrl <- trainControl(method = "repeatedcv", number = 5, repeats = 5)
```

```{r, performance_metric}
my_metric <- 'R-squared'
```

```{r, all_base_additive_feature_mod}
set.seed (8131999)
### z and t input polynomial with categorical input interaction.
mod8 <- train(logit_response ~ (I (z^5) + I (z^4) + I (z^3) + I (z^2) + z + I (t^5) + I (t^4) + I (t^3) + I (t^2) + t):m, 
                    data = efm_df,
                    method = "lm",
                    metric = my_metric,
                    trControl = my_ctrl)
```

### viewing results of nine non-bayesian models. 

```{r, view_non_bayesian_model_result}
#mod8$betas %>% dotplot (metric = "RMSE")
#mod8$betas %>% dotplot (metric = "R-squared")
#mod8$betas %>% dotplot (metric = "MAE")
mod8 %>% coefplot::coefplot () + theme_bw() + theme(legend.position='none')
```











```{r, save_model}
mod8 %>% readr::write_rds("linear_mod8_saved.rds")
```

```{r, reload_mod8}
re_load_mod8 <- readr::read_rds("linear_mod8_saved.rds")
```

```{r, show_reload_summary}
re_load_mod8 %>% summary()
```

```{r, check_mod8_equal}
all.equal( mod8, re_load_mod8)
```