---
title: "Final Project for 1675"
subtitle: "Linear Models: Part II b: bayesian mod9"
author: "David Spellman"
date: "12/5/2021"
output: html_document
---

## Loading packages

```{r, load_tidyverse}
library(tidyverse)
library(tidymodels)
library(mltools)
library(caret)
library(rstanarm)
library(performance)
```

## Reading in data

```{r, read_final_data}
df <- readr::read_csv("cs_1675_fall2021_finalproject.csv", col_names = TRUE)
```

```{r, build_data_frames}
dft <- df %>% mutate(logit_response = boot::logit (output)) %>% select (-output)
bfm_df <- dft
bf_df <- dft %>% select (-m)
efm_df <- dft %>% mutate (x5=(1-x1+x2+x3+x4), t=v1+v2, w=(x2/(x3+x4)), z=(x1+x2)/(x4+x5))
efm_df %>% glimpse()
ef_df <- efm_df %>% tibble::as_tibble () %>% select (-m)
```

```{r, make_cv_splits}
set.seed(1066)
cv_folds <- vfold_cv(efm_df, v = 5, repeats = 5, strata = logit_response)
cv_folds
```

### Apply Bayesian fitting for mod9

```{r}
mod_9_bayesian <- stan_lm(logit_response ~ (splines::ns(z, df=7)):m, 
                    data = efm_df, prior = R2(0.5))
```

```{r}
#model_performance(model = mod_6_bayesian, metrics = "all", verbose = TRUE)
pred_y <- predict(mod_9_bayesian, efm_df)
df_pred <- efm_df %>% mutate(pred=pred_y)
df_pred %>% ggplot(mapping=aes(x=z, y=logit_response)) +
    geom_point() +
    geom_line(mapping=aes(y=pred))

```

```{r}
bayesplot::color_scheme_set("viridis")
plot(mod_9_bayesian)
```

```{r, save_model}
mod_9_bayesian %>% readr::write_rds("linear_mod9_bayesian_saved.rds")
```

```{r, reload_mod9_bayesian}
re_load_mod9_bayesian <- readr::read_rds("linear_mod9_bayesian_saved.rds")
```

```{r, show_reload_summary}
re_load_mod9_bayesian %>% summary()
```

```{r, check_mod9_bayesin_equal}
all.equal(mod_9_bayesian, re_load_mod9_bayesian)
```