---
title: "Final Project for 1675"
subtitle: "Part II C: Linear Models: mod9 predictions"
author: "David Spellman"
date: "12/5/2021"
output: html_document
---

## Loading packages

```{r, load_tidyverse}
library(tidyverse)
library(tidymodels)
library(mltools)
library(caret)
```

## Reading in data

```{r, read_final_data}
df <- readr::read_csv("cs_1675_fall2021_finalproject.csv", col_names = TRUE)
```

```{r, build_data_frames}
#dft <- df %>% select (-output)
dft <- df %>% mutate (logit=boot::logit(output))
bfm_df <- dft
bf_df <- dft %>% select (-m)
efm_df <- dft %>% mutate (x5=(1-x1+x2+x3+x4), t=v1+v2, w=(x2/(x3+x4)), z=(x1+x2)/(x4+x5))
efm_df %>% glimpse()
ef_df <- efm_df %>% tibble::as_tibble () %>% select (-m)
```

```{r, reload_mod9}
pred_mod9 <- readr::read_rds("linear_mod9_saved.rds")

efm_df_fitted <- efm_df %>% mutate(fitted=as.vector(pred_mod9$finalModel$fitted.values))
mC_efm_df_fitted <- efm_df_fitted [efm_df_fitted$m == "C",]
mC_efm_df_fitted %>% ggplot(mapping=aes(x=z, y=logit)) +
  geom_point() +
  geom_line(mapping=aes(x=x1, y=fitted))

```

#### Model 9 does not appear to fit the data well relative to the z input.


```{r, graph_x1_x2_interaction}

efm_df_fitted %>% ggplot(mapping=aes(x=x1*x2, y=logit)) +
  geom_point() +
  geom_line(mapping=aes(x=x1*x2, y=fitted))

```

#### Model 9 achieve a tend very similar to model 6 with respect to the X1*X2 feature.



