---
title: "Final Project for 1675"
subtitle: "Part 5: Project Results and Analysis"
author: "David Spellman"
date: "12/5/2021"
output: html_document
---

## Loading packages

```{r, load_tidyverse}
library(tidyverse)
library(tidymodels)
library(mltools)
library(caret)
library(coefplot)
```

## Reading in data

```{r, read_pred_data}
df <- readr::read_csv("cs_1675_fall2021_holdout_inputs.csv", col_names = TRUE)
```

```{r, build_hold_data_frames}
hold_bfm_df <- df
hold_bf_df <- df %>% select (-m)
hold_efm_df <- df %>% mutate (x5=(1-x1+x2+x3+x4), t=v1+v2, w=(x2/(x3+x4)), z=(x1+x2)/(x4+x5))
hold_efm_df %>% glimpse()
hold_ef_df <- hold_efm_df %>% tibble::as_tibble () %>% select (-m)
```

```{r, read_test_train_data}
train_test_df <- readr::read_csv("cs_1675_fall2021_finalproject.csv", col_names = TRUE)
```

```{r, build_pred_data_frames}
indices <- sample (1:nrow(train_test_df), size = 200)
sample_df <- train_test_df %>% slice(indices)
pred_bfm_df <- sample_df
pred_bf_df <- sample_df %>% select (-m)
pred_efm_df <- sample_df %>% mutate (x5=(1-x1+x2+x3+x4), t=v1+v2, w=(x2/(x3+x4)), z=(x1+x2)/(x4+x5))
pred_efm_df %>% glimpse()
pred_ef_df <- pred_efm_df %>% tibble::as_tibble () %>% select (-m)
```

```{r, build_data_frames}
dft <- train_test_df %>% mutate(logit_response = boot::logit (output)) %>% select (-output)
bfm_df <- dft
bf_df <- dft %>% select (-m)
efm_df <- dft %>% mutate (x5=(1-x1+x2+x3+x4), t=v1+v2, w=(x2/(x3+x4)), z=(x1+x2)/(x4+x5))
efm_df %>% glimpse()
ef_df <- efm_df %>% tibble::as_tibble () %>% select (-m)
```

## Model comparison

```{r}
mod6 <- readr::read_rds("linear_mod6_saved.rds")
mod9 <- readr::read_rds("linear_mod9_saved.rds")
```

### Model 6 results
```{r}
mod6$results %>% glimpse()
```

### Model 9 results
```{r}
mod9$results %>% glimpse()
```

### The most important variables are z, x1, and x2

### Model 6 Regression Graphs
```{r}

efm_df_fitted6 <- efm_df %>% mutate(fitted=as.vector(mod6$finalModel$fitted.values))
efm_df_fitted6 %>% ggplot(mapping=aes(x=efm_df$z, y=logit_response)) +
  geom_point() +
  geom_line(mapping=aes(x=x1, y=fitted))

efm_df_fitted6 %>% ggplot(mapping=aes(x=x1*x2, y=logit_response)) +
  geom_point() +
  geom_line(mapping=aes(x=x1*x2, y=fitted))

```

### Model 9 Regression Graphs
```{r}

efm_df_fitted9 <- efm_df %>% mutate(fitted=as.vector(mod9$finalModel$fitted.values))
efm_df_fitted9 %>% ggplot(mapping=aes(x=efm_df$z, y=logit_response)) +
  geom_point() +
  geom_line(mapping=aes(x=x1, y=fitted))

efm_df_fitted9 %>% ggplot(mapping=aes(x=x1*x2, y=logit_response)) +
  geom_point() +
  geom_line(mapping=aes(x=x1*x2, y=fitted))

```

### Three of the machines gave a significant relationship for minamizing the value of the logit transformed response. The values that did this for m were B, C, and D. 

